[6CORE-075] Add reactive database support for Warehouse Service
sokimaaa/6Core pull request #117
Opened 2024-04-19 22:21 UTC by VictoriaKh-T

2024-04-20 19:27 UTC, sokimaaa requested changes

2024-04-20 19:27 UTC, sokimaaa commented on 3-platform/warehouse/infra/src/main/java/com/_6core/platform/warehouseinfra/adapter/driven/persistence/entity/InventoryEntity.java
> +  private int actualQuantity;
use wrapper classes pls for entity
```suggestion
  private Integer actualQuantity;
```

2024-04-20 19:27 UTC, sokimaaa commented on 3-platform/warehouse/infra/src/main/java/com/_6core/platform/warehouseinfra/adapter/driven/persistence/entity/InventoryEntity.java
> +  private String warehouseId;
Remember that this is Entity? (ORM)
```suggestion
  private Warehouse warehouse;
```

2024-04-21 16:06 UTC, sokimaaa requested changes

2024-04-21 16:06 UTC, sokimaaa commented on 3-platform/warehouse/infra/src/main/java/com/_6core/platform/warehouseinfra/adapter/driven/persistence/entity/InventoryEntity.java
> +@Data
Dont use @Data for Entity. 
```suggestion
@Setter
@Getter
```

2024-04-21 16:06 UTC, sokimaaa commented on 3-platform/warehouse/infra/src/main/java/com/_6core/platform/warehouseinfra/adapter/driven/persistence/entity/InventoryEntity.java
> +  }
```suggestion
```

2024-04-21 16:06 UTC, sokimaaa commented on 3-platform/warehouse/infra/src/main/java/com/_6core/platform/warehouseinfra/adapter/driven/persistence/entity/InventoryEntity.java
> +  private WarehouseEntity warehouse;
add @Transient for all dependencies. 

Check this guide to find out why:
https://medium.com/pictet-technologies-blog/reactive-programming-with-spring-data-r2dbc-ee9f1c24848b

2024-04-21 16:10 UTC, sokimaaa commented
Pls verify that your object-relational mapping work! 
Otherwise, what is the goal of this task? 

P.s. For example, create R2dbc repository, try to insert/update/get entities (with Join). To check that all is working! 
P.s.s. if you did some checks -> dont push them.

2024-04-21 16:12 UTC, VictoriaKh-T commented on 3-platform/warehouse/infra/src/main/java/com/_6core/platform/warehouseinfra/adapter/driven/persistence/entity/InventoryEntity.java
> +  private WarehouseEntity warehouse;
thank you, I had doubts about it

2024-04-21 18:05 UTC, sokimaaa commented on 3-platform/warehouse/infra/src/main/java/com/_6core/platform/warehouseinfra/adapter/driven/persistence/entity/InventoryEntity.java
> +  private WarehouseEntity warehouse;
pls in the future do research on your own. 

if you dont understand something - feel free to google (medium, baeldung, stackoverflow, ...)
On the web a lot of working examples.

2024-04-21 18:06 UTC, sokimaaa commented on 3-platform/warehouse/infra/src/main/resources/application.properties
dont create any properties in infra/app/domain modules.

2024-04-21 18:07 UTC, sokimaaa approved these changes

2024-04-21 18:08 UTC, VictoriaKh-T commented on 3-platform/warehouse/infra/src/main/java/com/_6core/platform/warehouseinfra/adapter/driven/persistence/entity/InventoryEntity.java
> +  private WarehouseEntity warehouse;
I googled and found it, and came to the conclusion that it is not needed. 
this is an example i found.
![зображення](https://github.com/sokimaaa/6Core/assets/100732681/fbf525e9-f822-4941-9d97-991c158ee8c0)

2024-04-22 07:13 UTC, YuraKhilko approved these changes

2024-04-22 07:45 UTC, merged