[6CORE-003] created skeleton of Order Management service
sokimaaa/6Core pull request #19
Opened 2024-03-04 18:09 UTC by kateryna-mykh

2024-03-06 09:39 UTC, sokimaaa requested changes

2024-03-06 09:39 UTC, sokimaaa commented on 3-platform/order-ms/app/pom.xml
> +            <version>0.0.1-SNAPSHOT</version>
bad name for groupId and artifactId. 
We have a bunch of services, and with such naming we have a lot of overlapping dependency (you are expecting here is order-related domain, someone else will expect the warehouse related domain).
Group Id describes company name, so you can left as it is. 
Change Artifact Id. 
```suggestion
            <groupId>com.6core.platform</groupId>
            <artifactId>domain</artifactId>
            <version>0.0.1-SNAPSHOT</version>
```

2024-03-06 09:39 UTC, sokimaaa commented on 3-platform/order-ms/app/src/main/java/com/core/platform/orderms/app/OrderUseCase.java
> +public final class OrderUseCase {
we don't need these dummy classes, leave packages empty, or add package-info.java to reflect package structure in git.

2024-03-06 09:39 UTC, sokimaaa commented on 3-platform/order-ms/app/src/main/java/com/core/platform/orderms/app/OrderUseCase.java
> +package com.core.platform.orderms.app;
bad naming of package -> it should be sum of groupId + artifactId. 
In java package names is reversed name of company, e.g. for mate.academy.com -> package name will `com.mate.academy`.
```suggestion
package com._6core.platform.orderms.app;
```

2024-03-06 09:39 UTC, sokimaaa commented on 3-platform/order-ms/pom.xml
> +</project>
remove all redundant classes. 
They were just examples of how it may look.

2024-03-08 11:10 UTC, sokimaaa approved these changes
You still need the approve from at least one team member.

2024-03-08 14:45 UTC, VictoriaKh-T approved these changes
Ok

2024-03-08 14:58 UTC, merged