[6CORE-0001] sceletion of warehouse
sokimaaa/6Core pull request #21
Opened 2024-03-06 21:31 UTC by VictoriaKh-T

2024-03-08 11:08 UTC, sokimaaa requested changes

2024-03-08 11:08 UTC, sokimaaa commented on 3-platform/warehouse/.gitignore
> +.git
there are already present .gitignore file in root directory, e.g. 6core/.gitignore. 

Modify it, to apply your changes globally

2024-03-08 11:08 UTC, sokimaaa commented on 3-platform/warehouse/app/pom.xml
> +        </dependency>
GroupId and ArtifactId will overlap in the future with other services and maven won't understand which artifact to get in project. 

Consider renaming your groupId/artifactId to be uniqe. 
for example: 
```
        <dependency>
            <groupId>com.6core.platform</groupId>
            <artifactId>warehouse-domain</artifactId>
            <version>0.0.1-SNAPSHOT</version>
        </dependency>
```

2024-03-08 11:08 UTC, sokimaaa commented on 3-platform/warehouse/app/pom.xml
> +        </dependency>
the same for app, infra, boot.

2024-03-08 11:08 UTC, sokimaaa commented on 3-platform/warehouse/app/pom.xml
> +    </build>
according to hexagonal architecture, we should write our `application` layer in way to be independent of framework we are using. 
Remove all spring-related dependency on layers app, domain
```suggestion
```

2024-03-11 15:11 UTC, kateryna-mykh commented on 2-library/domain-model-6core-java/src/main/java/com/_6core/lib/java/domain/model/order/Order.java
Why did you change this file?

2024-03-11 15:11 UTC, kateryna-mykh commented on 3-platform/warehouse/README.md
Usually, README starts with the header, not plain text.

2024-03-11 15:11 UTC, kateryna-mykh commented on .gitignore
While merging, you can have a problem with @YuraKhilko changes to the same file. So please, solve it with him.

2024-03-11 15:11 UTC, kateryna-mykh commented on 3-platform/warehouse/pom.xml
Just a suggestion: I'm not sure about dependency from artefactId name and name of the package, because I created projects through spring initializer. Could @sokimaaa, approve or comment on this?

2024-03-11 15:22 UTC, YuraKhilko commented on .gitignore
I've just copied all content from .gitignore file (generated by maven) to common .gitignore file and removed duplicates. 
My new  .gitignore file:
https://github.com/sokimaaa/6Core/pull/20/files#diff-bc37d034bad564583790a46f19d807abfe519c5671395fd494d8cce506c42947

2024-03-11 15:41 UTC, VictoriaKh-T commented on 2-library/domain-model-6core-java/src/main/java/com/_6core/lib/java/domain/model/order/Order.java
I changed it when we create test PR.  It 
stretched from there. There is no special changing.

2024-03-11 18:08 UTC, VictoriaKh-T commented on .gitignore
@YuraKhilko  your option is more advanced. I copied it.

2024-03-11 20:09 UTC, sokimaaa commented on 3-platform/warehouse/pom.xml
looks okay to me. 

generally, groupId points to the domain of the company, e.g. `6core.com`, `platform.6core.com`, `library.6core.com`. 
artifactId points to the type of program + what it is (library, platform, specification, domain, processor). 

You always can check how it was implemented in Spring Boot.

2024-03-11 20:10 UTC, sokimaaa approved these changes

2024-03-11 20:36 UTC, kateryna-mykh approved these changes

2024-03-11 20:56 UTC, merged