[6CORE-027]  Create REST Specification for Warehouse Service: Product Modification
sokimaaa/6Core pull request #50
Opened 2024-03-15 13:22 UTC by VictoriaKh-T

2024-03-15 17:03 UTC, sokimaaa requested changes

2024-03-15 17:03 UTC, sokimaaa commented on 3-platform/warehouse/app/pom.xml
> +    <artifactId>app</artifactId>
dont need to revert this!! 
We have already passed why. 
```suggestion
    <artifactId>app</artifactId>
```

2024-03-15 17:03 UTC, sokimaaa commented on 3-platform/warehouse/pom.xml
> +    </dependencies>
move this dependency to module where it is going to be used, e.g. `infra`
```suggestion
```

2024-03-15 17:03 UTC, sokimaaa commented on 3-platform/warehouse/spec/src/main/java/com/_6core/platform/warehouse/rest/v1/dto/ProductResponseDto.java
> +@Data
we have `record` in Java 17. 
```suggestion
```

2024-03-15 17:03 UTC, sokimaaa commented on 3-platform/warehouse/spec/src/main/java/com/_6core/platform/warehouse/rest/v1/dto/ProductResponseDto.java
> +    private String description;
formatting issue
```suggestion
    private Long Id;
    private String name;
    private BigDecimal price;
    private String description;
```

2024-03-15 17:03 UTC, sokimaaa commented on 3-platform/warehouse/spec/src/main/java/com/_6core/platform/warehouse/rest/v1/ProductModificationSpecification.java
> +            @ApiResponse(responseCode = "401", description = "Unauthorized", content = @Content),
Remove @Conten if empty
```suggestion
            @ApiResponse(responseCode = "401", description = "Unauthorized"),
```

2024-03-15 17:03 UTC, sokimaaa commented on 3-platform/warehouse/spec/src/main/java/com/_6core/platform/warehouse/rest/v1/ProductModificationSpecification.java
> +    @PutMapping("/products/{productId}/description")
PUT or PATCH? Explore difference, you can reach out to YUrii, he well knows this topic. 
```suggestion
    @PutMapping("/products/{productId}/description")
```

2024-03-15 17:03 UTC, sokimaaa commented on 3-platform/warehouse/spec/src/main/java/com/_6core/platform/warehouse/rest/v1/ProductModificationSpecification.java
> +            @RequestBody String newDescription
Create DTO Object for request!
Even if there is only String.
```suggestion
            @RequestBody String newDescription
```

2024-03-15 17:03 UTC, sokimaaa commented on 3-platform/warehouse/spec/src/main/java/com/_6core/platform/warehouse/rest/v1/ProductModificationSpecification.java
> +    public default Mono<ProductResponseDto> updateProductDescription(
Add response entity.  Reach out to the team if you don't understand why we need it. We discussed it before. 
```suggestion
    public default Mono<ResponseEntity<ProductResponseDto>> updateProductDescription(
```

2024-03-15 17:03 UTC, sokimaaa commented on 3-platform/warehouse/spec/src/main/java/com/_6core/platform/warehouse/rest/v1/ProductModificationSpecification.java
> +    public default Mono<ProductResponseDto> updateProductName(
`public` in interfaces is redundant. It sets by default. 
```suggestion
    default Mono<ProductResponseDto> updateProductName(
```

2024-03-15 17:03 UTC, sokimaaa commented on 3-platform/warehouse/spec/src/main/java/com/_6core/platform/warehouse/rest/v1/ProductModificationSpecification.java
> +
empty line
```suggestion
```

2024-03-15 17:03 UTC, sokimaaa commented on 3-platform/warehouse/spec/src/main/java/com/_6core/platform/warehouse/rest/v1/dto/ProductResponseDto.java
> +public class ProductResponseDto {
we have three independent units of functionality. 
1. Modify price
2. Modify description
3. Modify name

If we have (1), I am going to receive response with price-related information. 
The same for (2), (3). 

Any sense to have all in the one place, remember about SOLID (SRP).

2024-03-15 17:03 UTC, sokimaaa commented on 3-platform/warehouse/spec/src/main/java/com/_6core/platform/warehouse/rest/v1/dto/ProductResponseDto.java
> +public class ProductResponseDto {
Let's get rid of `Dto` postfix in our naming. This postfix dont bring any additional information.
```suggestion
public class ProductResponse {
```

2024-03-15 17:03 UTC, sokimaaa commented on 3-platform/warehouse/spec/src/main/java/com/_6core/platform/warehouse/rest/v1/ProductModificationSpecification.java
> +            @ApiResponse(responseCode = "500", description = "Internal server error", content = @Content)
you have mentioned about `500` in this endpoint, but didn't in others. Let's stay consistent through all documentation.

2024-03-15 17:03 UTC, sokimaaa commented on 3-platform/warehouse/spec/pom.xml
> +        </dependency>
use `record` that is provided by Java 17 instead of @Data. 
```suggestion
```

2024-03-15 17:03 UTC, sokimaaa commented on 3-platform/warehouse/spec/src/main/java/com/_6core/platform/warehouse/rest/v1/ProductModificationSpecification.java
> +public interface ProductModificationSpecification {
Discuss with team members about how you name all `Specification` classes.

As I see, Kateryna is called this like `Api`, you call it `Specification`. 
It violates Clean Code principles (choose one name for similar operations). 
```suggestion
public interface ProductModificationSpecification {
```

2024-03-18 18:41 UTC, sokimaaa requested changes

2024-03-18 18:41 UTC, sokimaaa commented on 3-platform/warehouse/infra/pom.xml
> +            <version>3.2.3</version>
we are using BOM, let's spring decide the version
```suggestion
```

2024-03-18 18:41 UTC, sokimaaa commented on 3-platform/warehouse/spec/src/main/java/com/_6core/platform/warehouse/rest/v1/ProductModificationAPI.java
> +public interface ProductModificationAPI<T, K> {
Using generics like here is a bad idea. 
1. We don't have a clear understanding of ApiResponse(content=@Content(...)) for 200 code
2. summary/description will never cover all generic cases (of request or response) or will be ugly. 
3. You will get a spring error that URI must be different for different endpoints
```suggestion
public interface ProductModificationApi {
```

2024-03-18 18:41 UTC, sokimaaa commented on 3-platform/warehouse/infra/pom.xml
> +            <version>3.2.3</version>
didnt fixed: remove version 
```suggestion
```

2024-03-18 18:41 UTC, sokimaaa commented on 3-platform/warehouse/spec/src/main/java/com/_6core/platform/warehouse/rest/v1/dto/product/RequestProductDescription.java
> +public record RequestProductDescription(Long productId, String description) {
Remember about consistency in naming the same things -> https://github.com/sokimaaa/6Core/pull/34/files#diff-68e3389c734e0d8d9291a7033c39dd1517764fe154f3acce8c0facacb98a270f

Kateryna suggests placing in the end `Request` or `Response`. 
When I said that you need to review your teammate, The main goal was to make you see how your teammates doing the same things. And you staying consistent. 
```suggestion
public record ProductDescriptionRequest(Long productId, String description) {
```

2024-03-18 22:14 UTC, VictoriaKh-T commented on 3-platform/warehouse/spec/src/main/java/com/_6core/platform/warehouse/rest/v1/ProductModificationAPI.java
> +public interface ProductModificationAPI<T, K> {
Ok, thank you.

2024-03-19 18:55 UTC, sokimaaa approved these changes

2024-03-19 19:25 UTC, kateryna-mykh approved these changes

2024-03-19 19:28 UTC, merged