[6core 024] contract for supplying and allocation
sokimaaa/6Core pull request #57
Opened 2024-03-21 14:25 UTC by VictoriaKh-T

2024-03-21 18:35 UTC, kateryna-mykh requested changes

2024-03-21 18:35 UTC, kateryna-mykh commented on 3-platform/warehouse/spec/src/main/java/com/_6core/platform/warehousespec/rest/v1/InventorySupplyApi.java
> +        description = "REST specification for supplying ")
Space in the end of description

2024-03-21 18:35 UTC, kateryna-mykh commented on 3-platform/warehouse/spec/src/main/java/com/_6core/platform/warehousespec/rest/v1/InventorySupplyApi.java
> +            @ApiResponse(responseCode = "500", description = "Internal server error")
description difference

2024-03-21 18:35 UTC, kateryna-mykh commented on 3-platform/warehouse/spec/src/main/java/com/_6core/platform/warehousespec/rest/v1/InventoryTransferAPI.java
> +public interface InventoryTransferAPI {
One file is "..Api" other is "..API"

2024-03-21 18:35 UTC, kateryna-mykh commented on 3-platform/warehouse/spec/src/main/java/com/_6core/platform/warehousespec/rest/v1/InventoryTransferAPI.java
> +        description = "REST specification for allocation ")
whitespace in the end of description

2024-03-21 18:35 UTC, kateryna-mykh commented on 3-platform/warehouse/spec/src/main/java/com/_6core/platform/warehousespec/rest/v1/InventoryTransferAPI.java
> +            @PathVariable String inventoryId) {
in method above you add @Parameter(description  = "inventory ID") for @PathVariable, but not there, why?

2024-03-21 18:35 UTC, kateryna-mykh commented on 3-platform/warehouse/spec/src/main/java/com/_6core/platform/warehousespec/rest/v1/dto/inventory/InventorySupplyRequest.java
> +                                     Integer quality) {
in that record and in the others: is that should be quality or rather quantity?

2024-03-22 09:30 UTC, sokimaaa requested changes

2024-03-22 09:30 UTC, sokimaaa commented on 3-platform/warehouse/spec/src/main/java/com/_6core/platform/warehousespec/rest/v1/InventorySupplyApi.java
> +    @PatchMapping("inventory/{inventoryId}/supply")
REST URI naming violation. pls check https://restfulapi.net/resource-naming/

2024-03-22 09:30 UTC, sokimaaa commented on 3-platform/warehouse/spec/src/main/java/com/_6core/platform/warehousespec/rest/v1/InventoryTransferApі.java
> +    default Mono<ResponseEntity<InventoryTransferResponse>> transferInventory (
Not Transfering! `Allocation` is about creation of a new inventory spot for on merchant' request. 
```suggestion
    default Mono<ResponseEntity<InventoryTransferResponse>> transferInventory (
```

2024-03-22 09:32 UTC, sokimaaa requested changes

2024-03-22 09:32 UTC, sokimaaa commented on 3-platform/warehouse/spec/src/main/java/com/_6core/platform/warehousespec/rest/v1/InventoryTransferApі.java
> +    default Mono<ResponseEntity<InventoryTransferResponse>> transferInventory (
BTW: I think that `allocation` and `supply` could be merged into one interface. It is all about `management` of inventory. No need to create a new class per method.

2024-03-22 22:44 UTC, kateryna-mykh approved these changes

2024-03-23 16:28 UTC, sokimaaa requested changes

2024-03-23 16:28 UTC, sokimaaa commented on 3-platform/warehouse/spec/src/main/java/com/_6core/platform/warehousespec/rest/v1/InventoryManagementApi.java
> +    @PostMapping("/inventory/allocate")
Fix URI regarding REST URI naming Conventions for both allocation and supply.
https://restfulapi.net/resource-naming/

https://medium.com/@nadinCodeHat/rest-api-naming-conventions-and-best-practices-1c4e781eb6a5
```suggestion
    @PostMapping("/inventory/allocate")
```

2024-03-24 11:52 UTC, sokimaaa requested changes

2024-03-24 11:52 UTC, sokimaaa commented on 3-platform/warehouse/spec/src/main/java/com/_6core/platform/warehousespec/rest/v1/InventoryManagementApi.java
> +    @PostMapping("/inventories/{inventoryId}/allocations")
REST typically provides the resources, e.g. inventories. This is why we name it in the plural.
Is `allocations` the resource? I don't think so. 

`Allocate` is verb and URI convention recommends getting rid of `verbs`. Why? We have methods like POST, PATCH, PUT ,... that say to us what endpoint is going to do. 
So adding the verb is redundant in this case. 

The same for other endpoints.
```suggestion
    @PostMapping("/inventories/{inventoryId}")
```

2024-03-24 11:52 UTC, sokimaaa commented on 3-platform/warehouse/spec/src/main/java/com/_6core/platform/warehousespec/rest/v1/InventoryManagementApi.java
> +    @PostMapping("/inventories/{inventoryId}/allocations")
you forgot about `warehouses/{warehouseId}`. Merchant is going to allocate space in the specific warehouse, isn't it?

2024-03-24 11:52 UTC, sokimaaa commented on 3-platform/warehouse/spec/src/main/java/com/_6core/platform/warehousespec/rest/v1/InventoryManagementApi.java
> +    @PatchMapping("/inventories/{inventoryId}/products")
Are we changing inventory or products? I think inventory.
You can remember, that DELETE, PUT, and PATCH methods apply only to a singular resource.
That means the last element in URI is going to be `somes/{someId}`

```suggestion
    @PatchMapping("/inventories/{inventoryId}")
```

2024-03-24 11:54 UTC, sokimaaa commented on 3-platform/warehouse/spec/src/main/java/com/_6core/platform/warehousespec/rest/v1/InventoryManagementApi.java
> +    @PostMapping("/inventories/{inventoryId}/allocations")
the same for supply. We need to have information about which warehouse was supplied

2024-03-26 18:11 UTC, sokimaaa approved these changes

2024-03-26 19:12 UTC, merged