[6CORE-045] create full copy of java domain model in protobuf format
sokimaaa/6Core pull request #85
Opened 2024-04-09 12:02 UTC by kateryna-mykh

2024-04-11 13:39 UTC, sokimaaa requested changes

2024-04-11 13:39 UTC, sokimaaa commented on 2-library/proto-domain-model/pom.xml
> +    </dependencies>
Do we need to have reactiveness in this library now? leave only necessary dependencies for now.

2024-04-11 13:39 UTC, sokimaaa commented on 2-library/proto-domain-model/pom.xml
> +    </dependencyManagement>
lets' use bom only in the 6core-bom library. For libs leave hardcoded value.

2024-04-12 08:07 UTC, sokimaaa approved these changes

2024-04-12 11:27 UTC, YuraKhilko approved these changes

2024-04-12 11:42 UTC, merged